package com.shigeodayo.ardrone.command;

public enum FlightAnimation {
	PHI_M30_DEG, PHI_30_DEG, THETA_M30_DEG, THETA_30_DEG, THETA_20DEG_YAW_200DEG, THETA_20DEG_YAW_M200DEG, TURNAROUND, TURNAROUND_GODOWN, YAW_SHAKE, YAW_DANCE, PHI_DANCE, THETA_DANCE, VZ_DANCE, WAVE, PHI_THETA_MIXED, DOUBLE_PHI_THETA_MIXED, FLIP_AHEAD, FLIP_BEHIND, FLIP_LEFT, FLIP_RIGHT;
}